#!/usr/bin/env python3
"""Render one_call and code_and_script prompt files for every DP problem.

The boilerplate (style block, string drawing rules, layout skeleton) lives here
once. Only the problem-specific content lives in specs.py. See
MASTER_ONE_CALL_DIAGRAM_PROMPT.md for why each rule is what it is.

    python3 dp/build_cards.py            # write all prompt files
    python3 dp/build_cards.py lcs lis    # write just these
"""

import sys
from pathlib import Path

from specs import PROBLEMS

PROMPTS = Path(__file__).parent / "prompts"

STYLE = """STYLE: a bright, fun classroom poster for a 10 year old, in friendly hand-drawn
marker lettering.
- Page background: soft warm cream with a faint pale dotted grid, plus a few
  small confetti dots and doodle stars in the empty areas.
- Every major box has a SOLID SATURATED colored header bar with its title in
  bold WHITE lettering, a soft pastel tint filling the body, a thick rounded
  outline and a soft drop shadow.
- Thick COLORED arrows matching the block they point to, big friendly
  arrowheads.
- Two or three BIG cute cartoon doodles with smiling faces and rosy cheeks,
  tucked into the margins so they never overlap text.
- A yellow sticky note with a red pushpin for the example.
- All lettering large, dark and crisp on the pale fills. Never shrink text."""

BARS = """HOW THE DATA IS DRAWN, VERY IMPORTANT:
Never draw the input as a row of individually coloured cells, and never write a
row of index numbers under it. That is visual noise. Instead:
- The input is ONE long flat rounded bar in plain neutral GREY, empty, with
  nothing written along it. Keep the bar LONG. The whole effect depends on one
  small bright square sitting on a long empty bar.
- Exactly ONE square sticks out of that bar: the current element, filled BRIGHT
  PURPLE with its value in bold white, and its index written under it ONLY in
  the CURRENT CALL box.
- Any part already used or dropped is pale grey, hatched, and crossed out.
- Never highlight two squares on the same bar."""

BARS_TWO_POINTER = """HOW THE DATA IS DRAWN, VERY IMPORTANT:
Never draw the input as a row of individually coloured cells, and never write a
row of index numbers under it. Instead:
- The input is ONE long flat rounded bar in plain neutral GREY, empty, with
  nothing written along it. Keep the bar LONG.
- TWO squares stick out of it, in DIFFERENT colours: the left pointer BRIGHT
  PURPLE, the right pointer TEAL, each showing its value in bold white and
  labelled with its own name.
- The span of bar BETWEEN the two squares is tinted pale yellow, labelled once
  with what is still in question.
- Anything outside the two pointers is pale grey, hatched, and crossed out."""

BADGES = """STEP BADGES: each step gets a big round numbered badge in the colour of that
step, on the top left corner of its block.

NO CODE PANEL. This page never shows the source code. The code lives on the
companion practice card, and repeating it here only competes with the diagram.
Do not draw a "THE CODE" box anywhere.

NO REDUNDANT NUMBERS IN THE TEXT. The concrete index or value is already shown
on the bar diagram, so never restate it in the sentences beside it. Write the
recursive call symbolically, in terms of the parameter name, and stop there.
This rule is about the WRITING ONLY. The bars keep every number they already
had, and a square that moves must show the value of its NEW position, not the
old one. Dropping numbers from the diagram is a mistake, not the goal."""


def loop_call(p):
    """Render a diagram for a recurrence that branches over a LOOP of choices.

    Coin Change, Word Break and Burst Balloons do not have two fixed branches.
    They try every option in turn and combine all the results, so the page fans
    out into three sample lanes with an "and so on" marker, then merges.
    """
    lanes = "\n\n".join(
        f"""   LANE {i + 1}, {lane['colour']}:
      A pill reading "{lane['label']}".
      Below it:
{lane['body']}
      Then a purple-outlined box, holding ONE line and nothing else:
         "{lane['expr']}\""""
        for i, lane in enumerate(p["lanes"])
    )

    return f"""{p['key'].upper()} ONE RECURSIVE CALL (landscape, loop of choices)
==============================================================
Landscape 1536x1024. Explains exactly ONE invocation of
{p['signature']}.

SHAPE: {p['shape_note']}
This one branches over a LOOP, not two fixed choices, so the page
fans into sample lanes and merges them all with one operator.
Generated by build_cards.py from specs.py.
==============================================================

================================================================================
PROMPT 1: One Recursive Call -> {p['key']}_one_call.png
================================================================================

Create a landscape hand-drawn educational infographic, 1536x1024.

{STYLE}

{BARS}

{BADGES}

TITLE across the top, very large, first words purple, rest black:
   "{p['title']}  -  ONE CALL"

TOP LEFT: a yellow sticky note with a red pushpin and a small target doodle:
   "THE EXAMPLE"
{p['example']}

TOP CENTER: box with a purple header bar reading "THE CALL ARRIVES".
   On its left, large purple lettering:
      "{p['call']}"
   under it, one small black line: "{p['promise']}"
   On its right:
{p['state']}
This box is WIDE. The top row of the page holds only two things, the sticky note
on the left and this box filling all the remaining width. There is no third box.

=== STEP 1, full width, blue, badge "1" ===

A wide band, solid BLUE header bar, white text: "STEP 1   {p['base_title']}".
Pale blue body, two short lines:
   "{p['base_case']}"
   "{p['base_why']}"
On the right end, a small green arrow curving down labelled
   "not done, keep going"

=== STEP 2, full width, blue, badge "2" ===

A centered SOLID BLUE pill, bold white lettering:
   "{p['question_pill']}"
Under it, one small black line: "{p['loop_note']}"

=== STEP 3, THE FAN OUT, badge "3" ===

From that pill, THREE thick coloured arrows fan downward into three narrow
lanes sitting side by side, each showing one option being tried. To the right
of the third lane, a large grey "..." with a small label "and so on for every
option", so it is clear the loop keeps going.

{lanes}

=== STEP 4, THE MERGE, full width at the bottom, purple, badge "4" ===

Every lane sends a thick arrow down into ONE wide box at the bottom centre.
Solid PURPLE header bar, white text: "{p['merge_title']}".
Pale purple body, with a shiny gold trophy doodle beside it. Large lettering:
   "return  {p['combine']}"
Under it, one short black line:
   "{p['combine_note']}"

=== CORNER BOX, no arrow touching it ===

A small box with an AMBER header bar reading "{p['corner']['title']}":
{p['corner']['body']}

COMPOSITION: one call at the top, then a wide fan of sample options, then every
lane funnelling back into a single answer. The "..." must make clear this is a
loop, not a fixed set of branches. Airy and colorful, every word spelled
correctly.
"""


def branch_var(branch):
    """The name the branch result is bound to, e.g. "one_step".

    Written on the card as `one_step -> climb( current_step + 1 )`, which ties
    the box to the name used in the final return without repeating the concrete
    index that the bar diagram above it already shows.
    """
    if branch.get("var"):
        return branch["var"]
    return branch["label"].lower().replace(" ", "_")


def one_call(p):
    """Render the frozen-call diagram prompt."""
    if p["shape"] == "loop":
        return loop_call(p)
    bars = BARS_TWO_POINTER if p.get("two_pointer") else BARS
    merge = p["shape"] == "choices"

    split = (
        """From that pill, two thick coloured arrows fan out, one curving down LEFT and
one curving down RIGHT, into two columns side by side. Green arrow to the left
column, red arrow to the right column. Between the columns, near the top, a
small PURPLE pill reading "both are explored". Do NOT draw a dashed divider,
and do NOT write "only one branch runs"."""
        if merge
        else """From that pill, two thick coloured arrows fan out, one curving down LEFT and
one curving down RIGHT, into two columns side by side that run to the bottom
and NEVER rejoin. Green arrow to the left column, red arrow to the right
column. Between them, a long vertical DASHED grey line with a small grey pill
on it reading "only one branch runs"."""
    )

    if merge:
        ending = f"""=== THE MERGE, full width at the bottom, purple ===

One thick GREEN arrow from the left column and one thick RED arrow from the
right column BOTH enter the same wide box at the bottom centre. This shared box
is the point: unlike an if / else, both choices really happen and are compared.
Solid PURPLE header bar, white text: "{p['merge_title']}".
Pale purple body, gold trophy doodle beside it. ONE line only, very large:
   "return  {p['combine']}"        in purple, with the operator biggest
Do not restate what each branch evaluated to. The two columns above already
named those, and repeating them here is the clutter to avoid.
Under it, one short black line:
   "{p['combine_note']}\""""
    else:
        ending = f"""A thick green arrow leads down to a green return box at the bottom of the LEFT
column, dark green lettering:
   "return  {p['branch_a']['ret']}"

A thick red arrow leads down to a red return box at the bottom of the RIGHT
column, red lettering:
   "return  {p['branch_b']['ret']}\""""

    corner = ""
    if p.get("corner"):
        corner = f"""
=== CORNER BOX, no arrow touching it ===

A small box with an AMBER header bar reading "{p['corner']['title']}":
{p['corner']['body']}
"""

    return f"""{p['key'].upper()} ONE RECURSIVE CALL (landscape)
==============================================================
Landscape 1536x1024. Explains exactly ONE invocation of
{p['signature']}.

SHAPE: {p['shape_note']}
Generated by build_cards.py from specs.py.
See MASTER_ONE_CALL_DIAGRAM_PROMPT.md for the rules behind this layout.
==============================================================

================================================================================
PROMPT 1: One Recursive Call -> {p['key']}_one_call.png
================================================================================

Create a landscape hand-drawn educational infographic, 1536x1024.

{STYLE}

{bars}

{BADGES}

TITLE across the top, very large, first words purple, rest black:
   "{p['title']}  -  ONE CALL"

TOP LEFT: a yellow sticky note with a red pushpin and a small target doodle:
   "THE EXAMPLE"
{p['example']}

TOP CENTER: box with a purple header bar reading "THE CALL ARRIVES".
   On its left, large purple lettering:
      "{p['call']}"
   under it, one small black line: "{p['promise']}"
   On its right:
{p['state']}
This box is WIDE. The top row of the page holds only two things, the sticky note
on the left and this box filling all the remaining width. There is no third box.

A thick arrow leads down the centre from THE CALL ARRIVES into:

=== STEP 1, full width, blue ===

A wide band, solid BLUE header bar, white text: "STEP 1   {p['base_title']}".
Big round blue badge "1". Pale blue body, two short lines:
   "{p['base_case']}"
   "{p['base_why']}"
On the right end, a small green arrow curving down labelled
   "not done, keep going"

=== STEP 2, full width, blue ===

A centered SOLID BLUE pill, bold white lettering, big round blue badge "2":
   "{p['question_pill']}"

=== THE SPLIT ===

{split}

=== LEFT COLUMN (green), badge "3" ===

Solid GREEN header bar, white text: "{p['branch_a']['title']}".
Pale green body:
{p['branch_a']['body']}
   Then a purple-outlined box{' with a gold starburst around the added value' if p['branch_a'].get('adds') else ''}, holding ONE line and nothing else:
      "{branch_var(p['branch_a'])}   ->   {p['branch_a']['expr']}"
   Then one short black line: "{p['branch_a']['change']}"

=== RIGHT COLUMN (red), badge "4" ===

Solid RED header bar, white text: "{p['branch_b']['title']}".
Pale red body:
{p['branch_b']['body']}
   Then a purple-outlined box, holding ONE line and nothing else:
      "{branch_var(p['branch_b'])}   ->   {p['branch_b']['expr']}"
   Then one short black line: "{p['branch_b']['change']}"

{ending}
{corner}
COMPOSITION: the page reads top to bottom in the exact order the code runs.
Airy and colorful, calm grey bars with a single bright highlight drawing the eye
in each row. Every word spelled correctly.
"""


def code_and_script(p):
    """Render the practice card prompt."""
    lines = "\n\n".join(
        f"   {dot} dot:\n      \"{text}\"" for dot, text in p["script"]
    )
    return f"""{p['key'].upper()} CODE AND THE SPOKEN IDEA (practice card)
==============================================================
Landscape 1536x1024. Two panels.
LEFT  : the real code, colourful, syntax highlighted.
RIGHT : FOUR short spoken lines, very large. Nothing else.

Voice: first person, active, present tense, plain words. The third
line names the UNCERTAINTY that forces the branching.
Generated by build_cards.py from specs.py.
==============================================================

================================================================================
PROMPT 1: Code and Spoken Idea -> {p['key']}_code_and_script.png
================================================================================

Create a landscape hand-drawn educational infographic, 1536x1024.

{STYLE}

TITLE across the top, very large, first words purple, rest black:
   "{p['title']}  -  THE CODE,  AND THE ONE IDEA"

The page is split into TWO TALL PANELS side by side, each about half the width,
both running the full height under the title.

=== LEFT PANEL: THE CODE ===

Dark slate header bar, white text: "THE CODE".
Body is a very pale grey code card with a thin rounded border, in a neat
monospace-looking hand, with soft colour coding: keywords in purple, the
function name in blue, numbers in orange, parameter names in dark teal, string
values in dark red. Small line numbers down the left edge in faint grey. No
badges on the code.

{p['code']}

Under the code card, a small grey chip:
   "start with   {p['start']}"

=== RIGHT PANEL: THE SPOKEN IDEA ===

Solid GREEN header bar, white text: "SAY THIS OUT LOUD".
Pale green body.

THE MOST IMPORTANT RULE FOR THIS PANEL: only the FOUR lines below appear here.
Write nothing else. No headings, no sub-labels, no extra sentences, no example
values. The lettering must be VERY LARGE, much bigger than the code on the left,
with generous empty space between the lines, because these lines are meant to be
read aloud from across a room.

The FOUR lines are stacked down the panel, each with a small round coloured dot
in front of it, each on its own two or three lines of big handwriting:

{lines}

Colour the key words inside those lines so the shape of the idea pops:
{p['script_colours']}

At the very bottom of the right panel, one small grey chip, in noticeably
smaller lettering so it clearly sits apart from the four spoken lines:
   "{p['footer_chip']}"

COMPOSITION: dense colourful code on the left, and a short spoken script on the
right in big airy lettering with lots of white space. The right panel should
look almost empty compared to the left. Every word spelled correctly.
"""


def main():
    wanted = sys.argv[1:]
    written = 0
    for p in PROBLEMS:
        if wanted and p["key"] not in wanted:
            continue
        (PROMPTS / f"{p['key']}_one_call.txt").write_text(one_call(p))
        (PROMPTS / f"{p['key']}_code_and_script.txt").write_text(code_and_script(p))
        print(f"  {p['key']:<12} {p['title']}")
        written += 2
    print(f"{written} prompt files written to {PROMPTS}")


if __name__ == "__main__":
    main()
