#!/usr/bin/env python3
"""Regenerate the "One Call" section of dp_workshop.html from specs.py.

Splices between the ONECALL-START and ONECALL-END markers, so re-running after
adding a problem to specs.py updates the page without touching anything else.

    python3 dp/gen_onecall_html.py            # rewrite the section
    python3 dp/gen_onecall_html.py --check    # report only, change nothing
"""

import html
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from specs import PROBLEMS

ROOT = Path(__file__).parent.parent
PAGE = ROOT / "dp_workshop.html"
IMAGES = ROOT / "dp" / "images"

START = "<!-- ONECALL-START, generated by dp/gen_onecall_html.py -->"
END = "<!-- ONECALL-END -->"

# The three cards whose prompts were hand written before specs.py existed.
EXTRA = {
    "lcs": {
        "title": "Longest Common Subsequence", "lc": 1143,
        "question": "Given two strings, return the length of their longest common "
                    "subsequence. A subsequence keeps the original order but may "
                    "skip characters.",
        "html_shape": "An if / else. The letter comparison picks the branch, so only "
                      "one runs and the two sides never merge.",
    },
    "lis": {
        "title": "Longest Increasing Subsequence", "lc": 300,
        "question": "Given an array of numbers, return the length of the longest "
                    "strictly increasing subsequence.",
        "html_shape": "Two real choices merged with max. Taking is gated by whether "
                      "the number beats the one being carried, and a blocked take is "
                      "worth zero so the max still works.",
    },
    "palsub": {
        "title": "Palindromic Substrings", "lc": 647,
        "question": "Given a string, count how many of its substrings are palindromes. "
                    "Substrings at different positions count separately even if they "
                    "read the same.",
        "html_shape": "An if / else, and lopsided. A match recurses inward, a mismatch "
                      "is a dead stop that never recurses at all.",
    },
}

# Display order. Mirrors the "26 Problems by Family" tab, with the 0/1 knapsack
# family grouped just before Target Sum, its representative in that list.
ORDER = [
    "stairs", "mincost", "decode", "maxprod", "robber", "robber2",
    "knapsack", "subsetsum", "equalpartition", "countsubsets",
    "minsubsetdiff", "targetsum",
    "coinchange", "coinchange2", "wordbreak",
    "longestpal", "palsub",
    "lcs", "editdistance", "interleaving", "distinctsubseq", "regex",
    "uniquepaths",
    "stock", "lis",
    "burst",
]

TITLES = {
    "stairs": "Climbing Stairs", "mincost": "Min Cost Climbing Stairs",
    "decode": "Decode Ways", "maxprod": "Maximum Product Subarray",
    "robber": "House Robber", "robber2": "House Robber II",
    "knapsack": "0/1 Knapsack", "subsetsum": "Subset Sum",
    "equalpartition": "Equal Sum Partition",
    "countsubsets": "Count of Subsets with Sum",
    "minsubsetdiff": "Minimum Subset Sum Difference",
    "targetsum": "Target Sum", "coinchange": "Coin Change",
    "coinchange2": "Coin Change II", "wordbreak": "Word Break",
    "longestpal": "Longest Palindromic Substring",
    "editdistance": "Edit Distance", "interleaving": "Interleaving String",
    "distinctsubseq": "Distinct Subsequences",
    "regex": "Regular Expression Matching", "uniquepaths": "Unique Paths",
    "stock": "Best Time to Buy & Sell Stock with Cooldown",
    "burst": "Burst Balloons",
}


def entries():
    by_key = {p["key"]: p for p in PROBLEMS}
    by_key.update(EXTRA)
    out, missing = [], []
    for key in ORDER:
        p = by_key.get(key)
        if not p:
            missing.append(key)
            continue
        title = p.get("title") if key in EXTRA else TITLES.get(key, key)
        out.append({
            "key": key,
            "title": title,
            "lc": p.get("lc", 0),
            "question": p["question"],
            "shape": p["html_shape"],
            "images": [f"dp/images/{key}_{kind}.png"
                       for kind in ("one_call", "code_and_script")],
        })
    return out, missing


def render(items):
    rows = []
    for e in items:
        num = f' <span class="lcnum">#{e["lc"]}</span>' if e["lc"] else ""
        imgs = []
        for path in e["images"]:
            kind = ("the frozen call, read in the order the code runs"
                    if path.endswith("one_call.png")
                    else "the code beside four sentences to say out loud")
            exists = (ROOT / path).exists()
            if not exists:
                continue
            imgs.append(
                f'<img src="{path}" alt="{html.escape(e["title"])}: {kind}" '
                f'class="scene-img" loading="lazy">'
            )
        rows.append(
            f'<div class="onecall" id="oc-{e["key"]}">\n'
            f'<h3>{html.escape(e["title"])}{num}</h3>\n'
            f'<div class="oc-q">{html.escape(e["question"])}</div>\n'
            f'<div class="oc-shape"><strong>Shape:</strong> '
            f'{html.escape(e["shape"])}</div>\n'
            + "\n".join(imgs) + "\n</div>"
        )
    intro = (
        '<h2>One Call, and How to Say It</h2>\n'
        '<p style="color:var(--muted)">Two pages per problem. The first freezes a '
        'single recursive call and reads top to bottom in the order the code runs: '
        'base case, then the condition, then the branch that fires. The second pairs '
        'the code with four sentences to say out loud, so you can explain the idea '
        'before writing a line. The <strong>Shape</strong> line on each card is the '
        'thing worth carrying between problems.</p>'
    )
    return START + "\n" + intro + "\n\n" + "\n\n".join(rows) + "\n" + END


def main():
    items, missing = entries()
    page = PAGE.read_text()
    if START not in page or END not in page:
        sys.exit(f"Markers not found in {PAGE.name}. Add {START} and {END}.")

    total_imgs = sum(len(e["images"]) for e in items)
    have = sum(1 for e in items for p in e["images"] if (ROOT / p).exists())
    print(f"{len(items)} problems, {have}/{total_imgs} images present")
    if missing:
        print("  no spec for:", ", ".join(missing))
    for e in items:
        gaps = [p for p in e["images"] if not (ROOT / p).exists()]
        if gaps:
            print(f"  {e['key']:<16} missing {len(gaps)}")

    if "--check" in sys.argv:
        return

    head, _, rest = page.partition(START)
    _, _, tail = rest.partition(END)
    PAGE.write_text(head + render(items) + tail)
    print(f"wrote section into {PAGE.name}")


if __name__ == "__main__":
    main()
